#api keys
FB_PAGE_ACCESS_TOKEN = ''
FB_VERIFY_TOKEN = ''
APIAI_CLIENT_ACCESS_TOKEN = ''
APIAI_SUBSCRIPTION_KEY = ''
WATSON_USERNAME = ''
WATSON_PASSWORD = ''
WATSON_API_VERSION = ''

#db settings
REDIS_PORT = 6379
REDIS_HOST = 'localhost'
